import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/context/theme-provider";
import { Toaster } from "sonner";
import { AuthProvider } from "@/context/AuthContext";
import Header from "@/components/header";
import { ChatsProvider } from "@/context/ChatsContext";
import { UsersProvider } from "@/context/UsersContext";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased
    box-border
    m-0
        `}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <Toaster position="top-center" />
          <AuthProvider>
            <UsersProvider>
              <ChatsProvider>
                <div className="min-h-screen w-full flex flex-col">
                  <Header />
                  <main className="flex flex-col flex-1">{children}</main>
                </div>
              </ChatsProvider>
            </UsersProvider>
          </AuthProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
